const Map<String, String> menuRoutes = {
  'Dashboard': '/dashboard',
  'Company': '/company',
  'Plant': '/plant',
  'Tank': '/tank',
  'Device': '/device',
  'Product': '/product',
  'User': '/user',
  'Group': '/group',
  'Rule': '/rule',
  'Message Template': '/message-template',
  'Roaster': '/roaster',
  'Report': '/report',
  'Asset Summary': '/asset-summary',
  'Schedule': '/asset-schedule',
  'Profile': '/profile',
  'Alarm': '/alarm',
  'Event': '/event',
  'Setting': '/setting',
};